stages:
  - build
  - upload

build:
  stage: build
  tags:
    - nix
  only:
    - trunk
  script:
    - nix develop -c bash build.sh
  artifacts:
    paths:
      - mac-mgmt.tar.gz

upload_dev:
  stage: upload
  tags:
    - nix
  only:
    - trunk
  needs:
    - build
  script:
    - nix develop -c bash upload.sh dev

upload_prod:
  stage: upload
  tags:
    - nix
  only:
    - prod
  needs:
    - build
  script:
    - nix develop -c bash upload.sh prod
