services:
  test-mac-mgmt-server:
    image: test-mac-mgmt-server:latest
    container_name: test-mac-mgmt-server
    tmpfs:
      - /run
      - /run/lock
      - /tmp

    networks:
      - mac-mgmt-test

  test-mac-mgmt-relay:
    image: test-mac-mgmt-relay:latest
    container_name: test-mac-mgmt-relay
    tmpfs:
      - /run
      - /run/lock
      - /tmp

    depends_on:
      - test-mac-mgmt-server
    networks:
      - mac-mgmt-test

  test-mac-mgmt-daemon:
    image: test-mac-mgmt-daemon:latest
    container_name: test-mac-mgmt-daemon
    tmpfs:
      - /run
      - /run/lock
      - /tmp

    depends_on:
      - test-mac-mgmt-server
      - test-mac-mgmt-relay
    networks:
      - mac-mgmt-test

networks:
  mac-mgmt-test:
    driver: bridge
