//! Embedded memvault-web frontend assets, served via rust-embed.
//!
//! The `WebAssets` struct is generated by build.rs, pointing at the dx client
//! output directory (or the `memvault-web-dist/` fallback). This avoids copying
//! files — the proc macro reads directly from the build output.

use std::path::PathBuf;

include!(concat!(env!("OUT_DIR"), "/web_assets_generated.rs"));

/// Extract all embedded assets to a temp directory and set `DIOXUS_PUBLIC_PATH`
/// so dioxus's `serve_dioxus_application` serves them.
/// Must be called before building the fullstack router.
pub fn prepare_public_dir() -> PathBuf {
    let dir = std::env::temp_dir().join("memvault-web-public");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("create memvault public dir");

    for file_path in WebAssets::iter() {
        if let Some(file) = WebAssets::get(&file_path) {
            let dest = dir.join(file_path.as_ref());
            if let Some(parent) = dest.parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            let _ = std::fs::write(&dest, &file.data);
        }
    }

    // SAFETY: called before the router is built, single-threaded init.
    unsafe { std::env::set_var("DIOXUS_PUBLIC_PATH", &dir) };
    dir
}
