[package]
name = "mac-mgmt-server"
version = "0.1.0"
edition = "2024"

[features]
default = ["web", "server", "webui"]
web = ["webui", "dioxus/web"]
webui = ["dep:dioxus", "dep:wasm-bindgen", "dep:dioxus-tabular"]
server = ["webui", "dioxus/server", "dep:axum-oidc-client", "dep:axum-extra", "dep:rocket", "dep:sqlx", "dep:tokio", "dep:sha2", "dep:hex", "dep:rand", "dep:tracing-subscriber", "dep:anyhow", "dep:toml", "dep:base64", "dep:reqwest", "dep:jsonschema", "dep:utoipa", "dep:utoipa-swagger-ui", "dep:schemars", "dep:similar", "dep:ed25519-dalek", "dep:pulldown-cmark", "dep:rust-embed"]
server-api-only = ["dep:rocket", "dep:sqlx", "dep:tokio", "dep:sha2", "dep:hex", "dep:rand", "dep:tracing-subscriber", "dep:anyhow", "dep:toml", "dep:base64", "dep:reqwest", "dep:jsonschema", "dep:utoipa", "dep:utoipa-swagger-ui", "dep:schemars", "dep:ed25519-dalek"]

[dependencies]
dioxus = { version = "0.7", features = ["fullstack", "router"], optional = true }
wasm-bindgen = { version = "=0.2.114", optional = true }
rocket = { version = "0.5", default-features = false, features = ["json"], optional = true }
utoipa = { version = "5", features = ["rocket_extras", "uuid", "chrono"], optional = true }
utoipa-swagger-ui = { version = "9", features = ["rocket"], optional = true }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"], optional = true }
tokio = { version = "1", features = ["full"], optional = true }
uuid = { version = "1", features = ["v4", "serde", "js"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
sha2 = { version = "0.10", optional = true }
hex = { version = "0.4", optional = true }
rand = { version = "0.9", optional = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", optional = true }
anyhow = { version = "1", optional = true }
toml = { version = "0.8", optional = true }
axum-oidc-client = { version = "0.3", features = ["sql-cache-postgres", "redis"], optional = true }
jsonschema = { version = "0.45", optional = true }
serde_json = "1"
base64 = { version = "0.22", optional = true }
axum-extra = { version = "0.10", features = ["cookie-private"], optional = true }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"], optional = true }
dioxus-tabular = { version = "0.3", optional = true }
ed25519-dalek = { version = "2", optional = true }
mac-mgmt-common = { path = "../common" }
schemars = { version = "1.2.1", features = ["derive"], optional = true }
similar = { version = "2", optional = true }
pulldown-cmark = { version = "0.12", optional = true }
rust-embed = { version = "8", features = ["include-exclude"], optional = true }
