use anyhow::{Context, Result};

use crate::managed_service::{ManagedService, TunnelDef};
use crate::sentry_ext;
use mac_mgmt_common::CloudConfig;
pub use mac_mgmt_common::LitellmConfig;

const CONFIG_FILENAME: &str = "litellm-config.yaml";

pub struct Litellm {
    config: LitellmConfig,
    cloud_cfgs: Vec<CloudConfig>,
}

impl Litellm {
    pub fn new(config: LitellmConfig, cloud_cfgs: Vec<CloudConfig>) -> Self {
        Self { config, cloud_cfgs }
    }

    fn effective_host(&self) -> &str {
        if self.config.host.is_empty() {
            "127.0.0.1"
        } else {
            &self.config.host
        }
    }

    fn effective_port(&self) -> u16 {
        if self.config.port == 0 {
            4100
        } else {
            self.config.port
        }
    }

    fn config_path() -> std::path::PathBuf {
        crate::config::config_dir().join(CONFIG_FILENAME)
    }

    /// Generate a LiteLLM YAML config from the enabled cloud providers.
    ///
    /// API keys are referenced via `os.environ/<VAR>` so they are passed
    /// through environment variables at spawn time, not written to disk.
    fn generate_config_yaml(&self) -> String {
        let mut yaml = String::from("# Auto-generated by mac-mgmt daemon — do not edit\n");
        yaml.push_str("model_list:\n");

        for cfg in &self.cloud_cfgs {
            if !cfg.enabled {
                continue;
            }
            let model = &cfg.default_model;
            let provider = cfg.provider.as_str();
            let base_url = cfg
                .base_url
                .as_deref()
                .filter(|s| !s.is_empty())
                .unwrap_or_else(|| cfg.provider.base_url());
            let env_var = cfg.provider.env_var();

            yaml.push_str(&format!("  - model_name: {model}\n"));
            yaml.push_str("    litellm_params:\n");
            yaml.push_str(&format!("      model: {provider}/{model}\n"));
            yaml.push_str(&format!("      api_key: os.environ/{env_var}\n"));
            yaml.push_str(&format!("      api_base: {base_url}\n"));
        }

        yaml.push_str("\ngeneral_settings:\n");
        if let Some(ref key) = self.config.master_key {
            yaml.push_str(&format!("  master_key: {}\n", key.expose()));
        }

        yaml.push_str("\nlitellm_settings:\n");
        yaml.push_str("  drop_params: true\n");
        yaml.push_str("  telemetry: false\n");

        yaml
    }

    /// Write the generated config YAML to disk.
    fn write_config(&self) -> Result<()> {
        let path = Self::config_path();
        let yaml = self.generate_config_yaml();
        std::fs::write(&path, &yaml)
            .with_context(|| format!("failed to write litellm config to {}", path.display()))?;
        tracing::info!("wrote litellm config to {}", path.display());
        Ok(())
    }

    async fn check_health_impl(&self) -> Result<bool> {
        match super::http_get(
            self.effective_host(),
            self.effective_port(),
            "/health/liveliness",
        )
        .await
        {
            Ok(body) if body.contains("\"status\"") => {
                tracing::debug!("litellm is healthy");
                Ok(true)
            }
            Ok(body) => {
                tracing::warn!("litellm unexpected health response: {body}");
                Ok(false)
            }
            Err(e) => {
                tracing::warn!(
                    "litellm health check failed at {}:{}: {e}",
                    self.effective_host(),
                    self.effective_port()
                );
                Ok(false)
            }
        }
    }

    /// Collect env vars with API keys for all enabled cloud providers.
    fn cloud_env(&self) -> std::collections::HashMap<String, String> {
        let mut env = std::collections::HashMap::new();
        for cfg in &self.cloud_cfgs {
            if !cfg.enabled {
                continue;
            }
            if let Some(ref key) = cfg.api_key {
                let val = key.expose();
                if !val.is_empty() {
                    env.insert(cfg.provider.env_var().to_string(), val.to_string());
                }
            }
        }
        env
    }
}

impl ManagedService for Litellm {
    fn name(&self) -> &str {
        "litellm"
    }

    fn ensure_installed(&self) -> Result<()> {
        if crate::nix::is_installed("litellm")? {
            tracing::info!("litellm is already installed");
            return Ok(());
        }

        tracing::info!("litellm not found, installing via nix");
        sentry_ext::breadcrumb(
            "install",
            "installing litellm via nix",
            &[("service", "litellm"), ("package", "litellm")],
        );
        crate::nix::profile_install("litellm", false)?;
        Ok(())
    }

    fn ensure_setup(&self) -> Result<()> {
        self.write_config()
    }

    fn configure(&self) -> Result<()> {
        tracing::info!("litellm: regenerating config (hot reload)");
        self.write_config()
    }

    fn supports_hot_reload(&self) -> bool {
        true
    }

    fn spawn_spec(&self) -> crate::managed_service::SpawnSpec {
        let config_path = Self::config_path();
        let mut env = self.cloud_env();
        // Disable telemetry
        env.insert("LITELLM_TELEMETRY".into(), "False".into());

        crate::managed_service::SpawnSpec {
            program: "litellm".into(),
            args: vec![
                "--config".into(),
                config_path.to_string_lossy().into_owned(),
                "--host".into(),
                self.effective_host().to_string(),
                "--port".into(),
                self.effective_port().to_string(),
            ],
            env,
        }
    }

    fn check_health(&self) -> Result<bool> {
        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(self.check_health_impl())
        })
    }

    fn check_health_async(
        &self,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<bool>> + Send + '_>> {
        Box::pin(self.check_health_impl())
    }

    fn repair(&self) -> Result<()> {
        // Regenerate config in case it was corrupted.
        self.write_config()?;
        Ok(())
    }

    fn check_and_upgrade(&self) -> Result<bool> {
        let upgradable = crate::nix::packages_with_upgrades(&["litellm"])?;
        if !upgradable.iter().any(|name| name == "litellm") {
            return Ok(false);
        }

        tracing::info!("upgrading litellm via nix");
        sentry_ext::breadcrumb(
            "upgrade",
            "upgrading litellm via nix",
            &[("service", "litellm"), ("package", "litellm")],
        );
        crate::nix::profile_install("litellm", true)?;
        tracing::info!("litellm upgraded, restart pending");
        Ok(true)
    }

    fn expose_tunnels(&self) -> Vec<TunnelDef> {
        vec![TunnelDef {
            name: "litellm".into(),
            host: self.effective_host().to_string(),
            tcp_port: self.effective_port(),
        }]
    }

    fn service_inventory(
        &self,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Vec<mac_mgmt_common::InventoryEntry>> + Send + '_>,
    > {
        Box::pin(async { Vec::new() })
    }

    fn service_sample(
        &self,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Vec<mac_mgmt_common::InventoryEntry>> + Send + '_>,
    > {
        Box::pin(async { Vec::new() })
    }

    fn service_security(
        &self,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Vec<mac_mgmt_common::SecurityFinding>> + Send + '_>,
    > {
        Box::pin(async { Vec::new() })
    }
}
