[package]
name = "mac-mgmt-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["ws"] }
axum-extra = { version = "0.10", features = ["typed-header"] }
futures-util = "0.3"
reqwest = { workspace = true }
rustls = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
async-stream = "0.3"
base64 = "0.22"
hex = "0.4"
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
tower = { version = "0.5", features = ["limit", "util"] }
tower-http = { version = "0.6", features = ["trace"] }
prometheus = "0.14"
prometheus-parse = "0.2"
protobuf = "3.7"
libp2p ={ version = "0.56", default-features = false, features = [
    "tokio", "noise", "yamux", "quic", "tcp", "websocket", "dns",
    "relay", "identify", "request-response", "ping", "gossipsub", "macros", "serde",
] }
libp2p-stream = "0.4.0-alpha"
tokio-tungstenite = "0.26"
tokio-util = { version = "0.7", features = ["compat"] }
russh = { version = "0.60", default-features = false, features = ["ring"] }
tokio-rustls = "0.26"
rustls-pemfile = "2"
sha2 = "0.10"
x509-parser = "0.16"
rcgen = "0.13"
hyper = { version = "1", features = ["server", "http1", "http2"] }
hyper-util = { version = "0.1", features = ["tokio"] }
mac-mgmt-common = { path = "../common" }
